# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: call-of-dshulhu.zip
        path: ./build/distributions/call-of-dshulhu.zip
    - name: compress bin archive
      run: zstd -19 ./build/distributions/call-of-dshulhu.tar
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: call-of-dshulhu.tar.zst
        path: ./build/distributions/call-of-dshulhu.tar.zst
